---
- hosts: localhost
  remote_user: root
  gather_facts: false
  vars_file: 
    - setup.yml
  tasks:
  - name: Create security group
    ec2_group:
        name: aws-ec2-ansible
        description: aws ec2-ansible security group
        region: us-east-1
        rules:
          - proto: tcp  # ssh
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # http
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # https
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: firewall_sg

  - name: Create a new EC2 key
    ec2_key:
      name: aws-ec2-ansible-key
      region: us-east-1
      key_material: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    
  - name: Create an EC2 instance
    ec2:
      key_name: aws-ec2-ansible-key
      region: us-east-1
      group_id: "{{ firewall_sg.group_id }}"
      instance_type: t2.micro
      image: ami-052efd3df9dad4825
      wait: yes
      instance_tags:
          Name: aws-ec2-ansible-key
      count_tag: Name
      exact_count: 1
      vpc_subnet_id: subnet-00ac03ba2b7bc09d2
      assign_public_ip: yes
    register: ec2
